# This is a basic workflow to help you get started with Actions

name: Iglu Server Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  iglu_file_patching:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Clone Quickstart Repo
        if: steps.cache-action.outputs.cache-hit != 'true'
        run: git clone https://github.com/snowplow/quickstart-examples.git ~/quickstart-examples

      - name: Verify we have our cached file
        run: ls ~/quickstart-examples
      # Runs a set of commands using the runners shell
      - name: Patching Iglu Vars File
        run: |
            bash -x ./scripts/patch_iglu_vars.sh
            echo "Terraform files have been patched with ENV Vars"
      - name: Patching Terraform Versions File
        run : |
            cp terraform_files/iglu/versions.tf ~/quickstart-examples/terraform/aws/iglu_server/default/versions.tf
            cat ~/quickstart-examples/terraform/aws/iglu_server/default/versions.tf
            echo "Terraform version file has been patched to save state to S3"
            echo "The API key is:${{secrets.AWS_DEFAULT_REGION}}"  

      - uses: actions/upload-artifact@master
        with:
          name: quickstart-examples
          path: ~/quickstart-examples/

  # This workflow contains a single job called "build"
  iglu_server_deployment:
    needs: iglu_file_patching
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.0.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.IAM_PERMISSIONS_BOUNDRY}}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: actions/download-artifact@master
        with:
          name: quickstart-examples
          path: ~/quickstart-examples/

      - run: ls ~/quickstart-examples

      - name: Patching Terraform Versions File
        run : |
            cd ~/quickstart-examples/terraform/aws/iglu_server/default
            echo "My current workspace is : $(pwd)" 
            echo "Lets Deploy the Server"
            terraform init
            terraform plan





